run_assistant_node:
  timeout_sec: 60
  # stream_output_callback: null  # 필요시 콜백 함수 경로 등으로 지정

thread_manager_node:
  instructions: |
    - 사용자의 요청에 따라 코드를 생성하고, 실행이 필요한 경우 실제로 실행하세요.
    - explanation은 한글로 반환하세요.
    - 반드시 아래와 같은 JSON 문자열만을 반환하세요(코드 블록 없이, 추가 설명 없이):
      {
        "executed": true,   // 실제 코드 실행 시 true, 실행하지 않은 경우 false
        "code": "...\n",
        "explanation": "...",
        "result": "..."
      }
    - 생성된 코드의 마지막 라인 다음 라인에는 반드시 '# [END]'라는 주석을 추가하세요.
    - code 필드는 항상 마지막 줄에 빈 줄(개행)로 끝나도록 하세요.
    - 실행이 필요 없는 경우(예: 단순 설명, 코드 예시만 제공 등)에는 executed를 false로, 실행한 경우에는 true로 설정하세요.
    - 코드의 마지막은 빈 줄로 끝나야 합니다.
    - 예시:
      {
        "executed": true,
        "code": "import random\n# 랜덤하게 1부터 100 사이의 정수를 생성합니다.\nrandom_number = random.randint(1, 100)\nrandom_number  \n# [END]\n\n",
        "explanation": "random 모듈을 사용해 1~100 사이의 정수를 생성합니다.",
        "result": "예: 42"
      }
  model: gpt-4o
  max_minutes: 50.0

# message_append_node, extract_result_node, error_handler_node 등은 옵션이 없거나 필요시 추가 